blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
  path('', views.post_list, name='post_list'),
  path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
  #path('', views.PostList.as_view(), name='post_list'),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
  path('<int:post_id>/share/', views.post_share, name='post_share'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
]



if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)                                

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
# Create your models here.

class PublishedManager(models.Manager):
  def get_queryset(self):
    return super(PublishedManager, self).get_queryset().filter(status='publish')

class Post(models.Model):
  STATUS_CHOICES = (
    ('draft','DRAFT'),
    ('publish','PUBLISH')
  )
  title = models.CharField(max_length=250)
  image = models.ImageField(upload_to='blog_posts/%y/%m/%d', blank=True)
  author = models.ForeignKey(User, 
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
  slug = models.SlugField(max_length=250,
                                        unique_for_date='publish')
  # body = models.TextField()   
  body = RichTextUploadingField(external_plugin_resources=[('youtube', '/static/vendors/ckeditor_plugins/youtube/', 'plugin.js',)])                                  
  publish = models.DateTimeField(default=timezone.now)
  created =  models.DateTimeField(auto_now_add=True)
  updated =  models.DateTimeField(auto_now=True)
  status = models.CharField(max_length=250,
                                        choices=STATUS_CHOICES, 
                                        default='draft')                                   


  objects = models.Manager() 
  published = PublishedManager() 
  tags = TaggableManager()  
  
  class Meta:
    ordering = ('-publish',) 

  def __str__(self):
    return self.title                                     

  def get_absolute_url(self):
    return reverse('blog:post_detail', args=[
                                              self.publish.year,
                                              self.publish.month,
                                              self.publish.day,
                                              self.slug,])


class Comment(models.Model):
  post =  models.ForeignKey(Post, 
                                  on_delete=models.CASCADE,
                                  related_name='comments') 
  name = models.CharField(max_length=80)
  email = models.EmailField()
  body = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True)

  class Meta:
    ordering= ('-created',)

  def __str__(self):
    return f'Comment by {self.name} on {self.post}'                                                                               

blog/forms.py
from django import forms
from .models import Comment

class EmailForm(forms.Form):
  name = forms.CharField(label=('Your Name'), max_length=250, 
                            widget=forms.TextInput(
                            attrs={}
                          )
                        )
  email = forms.EmailField(label='Your Email',
                            widget=forms.EmailInput(
                            attrs={'class':'validate'}
                          )
                        )
  to = forms.EmailField( label='Receiver Email',                           
                            widget=forms.EmailInput(
                            attrs={'class':'validate'}
                          )
                        )
  message = forms.CharField(label='Comment', required=False,
                            widget=forms.Textarea(
                            attrs={'class':'materialize-textarea'}
                          )
                        )

class CommentForm(forms.ModelForm):
    name = forms.CharField(label=('Name'), max_length=250, 
                          widget=forms.TextInput(
                          attrs={}
                        )
                      )
    email = forms.EmailField(label='Email',
                          widget=forms.EmailInput(
                          attrs={'class':'validate'}
                        )
                      )

    body = forms.CharField(label='Comment', required=False,
                          widget=forms.Textarea(
                          attrs={'class':'materialize-textarea'}
                        )
                      )
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
  search = forms.CharField(label='', 
                                widget=forms.TextInput(
                                attrs={ 'type':'search'
                                }
                              )
                            )

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
# Create your views here.

class PostList(ListView):
  queryset = Post.published.all()
  template_name = 'blog/post/list.html'
  paginate_by = 1
  context_object_name = 'posts'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
        #search
    form = SearchForm()
    query = None
    results = []
    if 'search' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['search']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B') #default weights are D, C, B AND A refer to 0.1, 0.2, 0.4, and 1.0 respectively
            search_query = SearchQuery(query)
            results = Post.objects.annotate(search=search_vector,
                                            rank=SearchRank(search_vector, search_query)
                                            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag':tag,
                   'form':form,
                    'query':query,
                    'results':results})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status='publish',
                                        publish__year=year,
                                        publish__month=month,
                                        publish__day=day,
                                        slug=post)
    #list of active comment  for the post
    comments = post.comments.filter(active=True)
    new_comment = None
    #list of similar  post
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:5]      
    if request.method == 'POST':
        #A commen was posted
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            #create comment object but don't save to databate yet
            new_comment = comment_form.save(commit=False)
            #Assign a current Post to the comment
            new_comment.post = post
            new_comment.save()
            
    else:
        comment_form = CommentForm()  

    return render(request, "blog/post/detail.html", 
                                                {'post':post,
                                                'comments':comments,
                                                'new_comment': new_comment,  
                                                'comment_form':comment_form,
                                                'similar_post':similar_post})    

def post_share(request,post_id):
    post = get_object_or_404(Post, status='publish', id=post_id)
    sent = False
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            # form field password validation
            cd = form.cleaned_data
            #send_mail...
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you reading '{post.title}'"
            message = f"Read '{post.title}' at {post_url}\n\n{cd['name']}'s comments: {cd['message']}"
            send_mail(subject, message, cd['email'], [cd['to']])
            sent=True
    else:
        form = EmailForm()        
    return render(request, "blog/post/share.html", 
                                                {'form':form,
                                                'post':post})

                                                                              

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }} | blOgeN{% endblock %}

{% block content %}
<!-- Comments forms and Modal -->

{% if new_comment %}
<div class="card-panel teal lighten-2">
  <h5 class="center white-text">Your comment has been added successfully!</h5>
</div>
{% else %}
<div id="modal1" class="modal">
  <div class="modal-content">
    <h5>Add a new Comment</h5>
    <form action="." method="post">{% csrf_token %}
      <div class="input-field teal-text">
        <i class="material-icons prefix">person</i>
        {{ comment_form.name }}
        {{ comment_form.name.label_tag }}
      </div>
      <div class="input-field teal-text">
        <i class="material-icons prefix">mail</i>
        {{ comment_form.email }}
        {{ comment_form.email.label_tag }}
      </div>
      <div class="input-field teal-text">
        <i class="material-icons prefix">comment</i>
        {{ comment_form.body }}
        {{ comment_form.body.label_tag }}
      </div>
      <div class="center">
        <input type="submit" value="Add Comment" class="btn-large waves-effect waves-light  z-depth-5">
      </div>
    </form>
  </div>
</div>
{% endif %}
<!-- Comment forms & Modal ends -->

<!-- Post Detail -->
<h4>{{ post.title }}</h4>
      <p class="grey-text">
        <i class="material-icons">person</i>
        {{ post.author }} |
        <i class="material-icons">publish</i>
        {{ post.publish.year }}/{{ post.publish.month }} |
        <i class="material-icons">comment</i>
        {{ post.comments.count }}
      </p>
      <hr />
<p>      
{{ post.body|markdown|safe }}
<p>
  <a href="{% url 'blog:post_share' post.id %}" class="btn-large right waves-effect waves-light waves-light  z-depth-5">
    <i class="material-icons right">screen_share</i>Share</a>
  <a href="#modal1" class="btn-large modal-trigger waves-effect waves-light  z-depth-5"><i class="material-icons left">comment</i>
    Comment</a>
</p>

<!-- Post Detail ends -->

<!-- Similar post -->
<h4>Similar Post</h4>
<div class="row">
  <div class="col s12">
    {% for post in similar_post %}
    <div class="card horizontal">
      <div class="card-image">
        {% if post.image %}
        <a href="{{ post.get_absolute_url }}">
          <img src="{{ post.image.url }}" alt="Post-Image">
        </a>
        {% endif %}
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <span class="card-title">{{ post.title|truncatewords:5 }}</span>
        </div>
      </div>
    </div>
    {% empty %}
    <p>There are no Similar Post yet.</p>
    {% endfor %}
  </div>
</div>
<!-- Similar post ends -->

<!-- Comment detail -->
<div class="card">
  <div class="card-content">
    <span class="card-title">
      {% with comments.count as total_comments %}
      {{ total_comments }} comment{{ total_comments|pluralize}}
      {% endwith %}</span>
    <table class="striped  responsive-table">
      <tbody>
        {% for comment in comments %}
        <tr>
          <th>{{ comment.name }}</th>
          <th>{{ comment.created.year}}/{{ comment.created.month}}</th>
          <th>{{ comment.body|linebreaks }}</th>
        </tr>
        {% empty %}
        <p class="red-text">There are no comments yet!</p>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- Comment detail ends -->
{% endblock %}

blog/templates/blog/post/latest_posts.html
{% load blog_tags %}
<ul class="collapsible">
    {% for post in latest_posts %}
    <li>
        <div class="collapsible-header teal-text">
            <i class="material-icons">visibility</i>
            {{ post.title }}
            <span class="badge new" data-badge-caption="new"></span>
        </div>
        <div class="collapsible-body">
            <div class="card">
                <div class="card-image">
                    {% if post.image %}
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="Post-Image">
                    </a>
                    {% endif %}
                </div>
                <div class="card-content">
                    <span class="card-title">{{ post.title }}</span>
                    <div class="card-action">
                        <a href="{{ post.get_absolute_url }}" class="center">Read</a>
                    </div>
                </div>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %} 
{% load blog_tags %} 
{% block title %}blOgeN{% endblock %} 
{% block content %}
  {% include 'blog/post/search.html' %}

  <!-- POST WITH TAGS HEDING -->
  {% if tag %}
  <div class="card-panel teal lighten-2">
    <h4 class="center white-text">Posts tagged with "{{ tag.name }}"</h4>
  </div>
  {% endif %}
  <!-- POST WITH TAGS HEDING ENDS -->

  {% for post in posts %} 
  {% include 'blog/post/list_snippet.html' %} 
  {% endfor %} 
  {% include 'pagination.html' with page=posts %}

{% endblock %}

blog/templates/blog/post/list_snippet.html
{% load blog_tags %}

<!-- CARD -->
<div class="card" style="background-color: #2b3e50;">
  <!-- Card image -->
  <div class="card-image">
    {% if post.image %}
    <a href="{{ post.get_absolute_url }}">
      <img src="{{ post.image.url }}" alt="Post Image">
    </a>
    {% endif %}
    <a class="btn-floating btn-large  red accent-3 pulse halfway-fab z-depth-5 activator waves-effect waves-light">
      <i class="material-icons">add</i></a>
  </div>
  <!-- Card image ends -->
  <!-- Card content -->
  <div class="card-content white-text">
    <span class="card-title activator center">
      {{ post.title }}
    </span>
    <h5>Tags <i class="material-icons">loyalty
      </i></h5>
    {% for tag in post.tags.all %}
    <div class="chip red accent-3">
      <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class='white-text'>
        {{ tag.name }}
      </a>
    </div>
    {% endfor %}
  </div>
  <!-- Card content ends -->
  <!-- Card reaveal -->
  <div class="card-reveal ">
    <span class="card-title center">
      {{ post.title }}
      <i class="material-icons right">close</i>
    </span>
    <div class="card-content">
      <blockquote>
        <h5>Tags <i class="material-icons">loyalty</i></h5>
      </blockquote>
      {% for tag in post.tags.all %}
      <div class="chip">
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
      </div>
      {% endfor %}
      <p class="grey-text">
        <i class="material-icons">person</i>
        {{ post.author }} |
        <i class="material-icons">publish</i>
        {{ post.publish.year }}/{{ post.publish.month }} | 
        <i class="material-icons">comment</i>
        {{ post.comments.count }}
      </p>
      <hr />
      <p>{{ post.body|markdown|safe|truncatewords_html:100 }}</p>
    </div>
    <!-- Card reaveal ends -->
    <!-- Card action -->
    <div class="card-action">
      <a href="{{ post.get_absolute_url }}" class="btn  red accent-3 z-depth-5 left waves-effect waves-light">
        <i class="material-icons left">visibility</i>read</a>
      <a href="{% url 'blog:post_share' post.id %}" class="btn red accent-3 z-depth-5 right waves-effect waves-light">
        <i class="material-icons right">screen_share</i>Share</a>
    </div>
    <!-- Card action ends -->
  </div>
</div>
<!-- CARD ENDS -->

blog/templates/blog/post/search.html
<!-- SEARCH BOX -->
<nav class="white">
  <div class="nav-wrapper">
    <form action="." method="get">
      <div class="input-field">
        {{ form }}
        <label><i class="material-icons blue-grey-text">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>

  </div>
</nav>
<!-- SEARCH BOX ENDS -->

<!-- RESULTS -->
{% if query %}
<div class="card-panel teal lighten-2">
  <h4 class="center white-text">Posts containing "{{ query }}"</h4>
</div>
<h5>
  {% with results.count as total_results %}
  Found {{ total_results }} result{{ total_results|pluralize}}
  {% endwith %}
</h5>
{% for post in results %}
{% include 'blog/post/list_snippet.html' %}
{% empty %}
<p class="red-text">There are no results for your query.</p>
{% endfor %}
<hr />
{% endif %}
<!-- RESULTS ENDS -->

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Sahre {{ post.title }} | blOgeN{% endblock %}

{% block content%}

<!-- EMAIL SENT SUCCESS MESSAGE -->
{% if sent %}
<div class="card-panel teal lighten-2">
  <h4 class="center white-text">E-mail Successfully sent</h4>
  <p class="center white-text">"{{ post.title }}" was Successfully sent to {{ form.cleaned_data.to}}</p>
</div>
{% else %}
<!-- MAIL SENT SUCCESS MESSAGE ENDS -->
<!-- SHARE POST HEADING -->
<div class="card-panel teal lighten-2">
  <h4 class="center white-text">Share "{{ post.title }}" by E-mail </h4>
</div>
<!-- SHARE POST HEADING ENDS -->
<!-- SHARE FORM -->
<div class="card-panel">
  <form action="/" method="post">{% csrf_token %}
    <div class="input-field teal-text">
      <i class="material-icons prefix">person</i>
      {{ form.name}}
      {{ form.name.label_tag }}
    </div>
    <div class="input-field teal-text">
      <i class="material-icons prefix">mail</i>
      {{ form.email}}
      {{ form.email.label_tag }}
    </div>
    <div class="input-field teal-text">
      <i class="material-icons prefix">mail</i>
      {{ form.to }}
      {{ form.to.label_tag }}
    </div>
    <div class="input-field teal-text">
      <i class="material-icons prefix">comment</i>
      {{ form.message}}
      {{ form.message.label_tag }}
    </div>
    <div class="center">
      <input  type="submit" value="Send E-mail" class="btn-large waves-effect waves-light  z-depth-5">
    </div>
  </form>
</div>
<!-- SHARE FORM ENDS -->
{% endif %}
{% endblock %}